replace all 32 bit with 64 bit because it's massively easier in MLIR

diff --git a/test/makefile b/test/makefile
--- a/test/makefile
+++ b/test/makefile
@@ -1,17 +1,5 @@
 .PHONY: fib fibstrict playground
 
-playround: 
-	make -C ~/work/mlir/coremlir/build
-	../build/bin/hask-opt ./playground.mlir -optimize  | tee playground-roundtrip.mlir
-	(../build/bin/hask-opt playground-roundtrip.mlir \
-		-optimize 1>/dev/null 2>/dev/null) \
-		|| (echo "===ROUNDTRIP FAILED==="; \
-			../build/bin/hask-opt playground-roundtrip.mlir; \
-			echo "===ROUNTRIP FAILED==="; false)
-	rm playground-roundtrip.mlir
-
-
-
 
 fibstrict: 
 	make -C ~/work/mlir/coremlir/build
@@ -21,6 +9,17 @@ fibstrict:
 	# ../build/bin/hask-opt ./fib-strict-roundtrip.mlir
 	# check that the optimized version runs
 	../build/bin/hask-opt ./fib-strict-roundtrip.mlir -optimize
+
+playground: 
+	make -C ~/work/mlir/coremlir/build
+	../build/bin/hask-opt ./playground.mlir -optimize  | tee playground-roundtrip.mlir
+	(../build/bin/hask-opt playground-roundtrip.mlir \
+		-optimize 1>/dev/null 2>/dev/null) \
+		|| (echo "===ROUNDTRIP FAILED==="; \
+			../build/bin/hask-opt playground-roundtrip.mlir; \
+			echo "===ROUNTRIP FAILED==="; false)
+	rm playground-roundtrip.mlir
+
 fib: 
 	make -C ~/work/mlir/coremlir/build
 	make -C ~/work/mlir/coremlir/ghc-dump
