[WIP] attr parsing

diff --git a/test/makefile b/test/makefile
--- a/test/makefile
+++ b/test/makefile
@@ -2,6 +2,16 @@
 # pipelines which involve tee and allow such pipelines to fail.
 .PHONY: fib fibstrict playground
 
+playground: 
+	make -C ~/work/mlir/coremlir/build
+	../build/bin/hask-opt ./playground.mlir -optimize  | tee playground-roundtrip.mlir
+	(../build/bin/hask-opt playground-roundtrip.mlir \
+		-optimize 1>/dev/null 2>/dev/null) \
+		|| (echo "===ROUNDTRIP FAILED==="; \
+			../build/bin/hask-opt playground-roundtrip.mlir; \
+			echo "===ROUNTRIP FAILED==="; false)
+	rm playground-roundtrip.mlir
+
 fib: 
 	make -C ~/work/mlir/coremlir/build
 	../build/bin/hask-opt ./fib.mlir
@@ -17,15 +27,6 @@ fibstrict:
 	# check that the optimized version runs
 	../build/bin/hask-opt ./fib-strict-roundtrip.mlir -optimize
 
-playground: 
-	make -C ~/work/mlir/coremlir/build
-	../build/bin/hask-opt ./playground.mlir -optimize  | tee playground-roundtrip.mlir
-	(../build/bin/hask-opt playground-roundtrip.mlir \
-		-optimize 1>/dev/null 2>/dev/null) \
-		|| (echo "===ROUNDTRIP FAILED==="; \
-			../build/bin/hask-opt playground-roundtrip.mlir; \
-			echo "===ROUNTRIP FAILED==="; false)
-	rm playground-roundtrip.mlir
 
 test-ops: 
 	make -C ~/work/mlir/coremlir/build
